"""m

Revision ID: 56e508514801
Revises: 
Create Date: 2025-03-22 22:00:33.292984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e508514801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashedPassword', sa.Text(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('usertype', sa.Integer(), nullable=False),
    sa.Column('avatarUrl', sa.Text(), nullable=True),
    sa.Column('openid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captcha', sa.Text(), nullable=False),
    sa.Column('createdTime', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_email_captcha_userId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_captcha'))
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operatorId', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operatorId'], ['user.id'], name=op.f('fk_log_operatorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('releaserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['releaserId'], ['user.id'], name=op.f('fk_notice_releaserId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    op.drop_table('log')
    op.drop_table('email_captcha')
    op.drop_table('user')
    # ### end Alembic commands ###
